org: viniciussfreire
app: lambda-img-analysis
service: lambda-img-analysis

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements: 
        - Effect: "Allow"
          Action:
            - rekognition:DetectLabels
          Resource: "*"
        - Effect: "Allow"
          Action:
            - translate:TranslateText
          Resource: "*"

functions:
  img-analysis:
    handler: handler.main
    events:
      - http:
          path: analyze
          method: get
